---
all:
  vars:
    ansible_host: 127.0.0.1
    ansible_port: 2222
    ansible_user: ubuntu
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null

  children:
    qemuvm:
      hosts:
        guest:
