#!/bin/bash

set -e

export HOST=${HOST:-$1}

if [ -z "$HOST" ]; then
	echo "USAGE: $0 HOST"
	exit 1
fi

shift 1

function change_to_build_dir {
	if [ ! -f ".config" ]; then
		cd ".build/$HOST"
	fi
}

if [ "$HOST" != "local" ]; then
	make_kern "$@" tar-pkg
	change_to_build_dir

	TARFILES=(linux-*localyes*.tar)
	if [ "${#TARFILES[@]}" != "1" ]; then
		>&2 echo "Too many tar files in your linux directory, clean them up!"
		exit 1
	fi
	TARFILE="${TARFILES[0]}"

	tar --delete -f "$TARFILE" --wildcards boot/vmlinux-*localyes*

	wait_for_host "$HOST"

	REMTARFILE=/tmp/linux.tar
	scp "$TARFILE" "$HOST":"$REMTARFILE"

	ssh "$HOST" sudo -s <<-EOF
		set -e
		rm -rf /lib/modules/*localyes*
		rm -f /boot/config-*localyes*
		tar -Oxf $REMTARFILE --wildcards boot/vmlinuz-*localyes* > \
			/boot/vmlinuz-9-localyes
		tar -Oxf $REMTARFILE --wildcards boot/config-*localyes* > \
			/boot/config-9-localyes
		tar -C / -xf $REMTARFILE --wildcards boot/config-*localyes*
		tar -C / -kxf $REMTARFILE lib
		rm -f $REMTARFILE
	EOF

	rm -f "$TARFILE"
else
	sudo -v
	make_kern "$@"
	change_to_build_dir

	sudo rm -rf /lib/modules/*localyes*
	sudo rm -f /boot/config-*localyes*
	sudo cp arch/x86/boot/bzImage /boot/vmlinuz-9-localyes
	sudo cp .config /boot/config-9-localyes
	sudo make modules_install
fi
