#!/bin/bash

# shellcheck source=setup_kern
source "${BASH_SOURCE[0]%/*}/setup_kern"
MAKE_PARAMS+=("-j100")

make "${MAKE_PARAMS[@]}" oldconfig

export PATH="/usr/lib/icecc/bin:$PATH"

if [[ "$*" == *menuconfig* ]]; then
	make "${MAKE_PARAMS[@]}" "$@"
else
	time make "${MAKE_PARAMS[@]}" "$@" 2>&1 | tee "$ODIR/make.log"
fi
