#!/bin/bash

# shellcheck source=./inst_kern
source "${BASH_SOURCE[0]%/*}/inst_kern"

if [ "$HOST" != "local" ]; then
	ssh "$HOST" sudo reboot
elif [ -f /lib/molly-guard/reboot ]; then
	sudo /lib/molly-guard/reboot
else
	sudo reboot
fi
