#!/bin/bash
#
# create-gcp-nested
#
# (C) Stephen Bates <sbates@raithlin>
#
# A simple script to generate an instance on Google Compute Platform
# (GCP) capable of nested virtualization. We will use this as a
# starting point for hosting VMs on top of this instance. Note the
# default here to use a Ubuntu RootFS on the instance. This simple
# script is based on [1].
#
# [1] https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances

NAME=${NAME:-google-nested}
SIZE=${SIZE:-512GB}

gcloud compute disks create ${NAME}-disk \
       --zone=us-central1-b --type=pd-standard \
       --image=ubuntu-1804-bionic-v20181222 \
       --image-project=ubuntu-os-cloud --size=${SIZE}

gcloud compute images create ${NAME}-image \
  --source-disk ${NAME}-disk \
  --source-disk-zone us-central1-b \
  --licenses "https://www.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"

gcloud compute instances create ${NAME}-vm \
       --zone us-central1-b \
       --image ${NAME}-image
