#!/bin/bash
#
# create-name
#
# (C) Stephen Bates <sbates@raithlin>
#
# A simple script to generate a ton of fake NVMe SSDS inside a QEMU
# VM. This script generates the files used to back the SSDs as well as
# a section of XML that should be added to the libvirt XML description
# of the VM. You also need to add the QEMU schema [1] and you might
# need to play with apparmor to make this all work.
#
# Note that if you set DIR=null we don't create backing files for the
# NVMe SSDs and instead use the null block driver inside QEMU. This
# leads to improved performance but obviously no actual storage.
#
# [1] http://blog.vmsplice.net/2011/04/how-to-pass-qemu-command-line-options.html
# [2] https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1772936
#
# Add this to your domain at the top:
# xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'

NUM=${NUM:-24}
DIR=${DIR:-/var/lib/libvirt/images}
SIZE=${SIZE:-128M}
CMB=${CMB:-0}
CREATE=${CREATE:-no}
PREFIX=${PREFIX:-none}

if [ $PREFIX != "none" ]; then
    PREFIX="${PREFIX}-"
else
    PREFIX=""
fi

  # Create the qcow2 image files for the NVMe SSDs.

if [ $CREATE == "yes" ]; then
    if [ ! -d $DIR ]; then
	echo "$DIR does not exist!"
	exit -1
    fi
    echo "Creating qcow2 image files for NVMe..."
    i=0
    while [ $i -lt $NUM ]; do
	if [ -f ${DIR}/${PREFIX}nvme${i}.qcow2 ]; then
	    echo "${DIR}/${PREFIX}nvme${i}.qcow2 already exists!"
	    exit -1
	fi
	qemu-img create -f qcow2 ${DIR}/${PREFIX}nvme${i}.qcow2 ${SIZE} > /dev/null
	((i++))
    done
    chown libvirt-qemu:kvm ${DIR}/${PREFIX}nvme*.*
    chmod 644 ${DIR}/${PREFIX}nvme*.*
    ls -lrth ${DIR}
fi

  # Echo the XML output for virsh edit

echo
echo "# Add this to your domain entry at the top of the xml:"
echo "# xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'"
echo
i=0
echo "  <qemu:commandline>"
while [ $i -lt $NUM ]; do
    echo "    <qemu:arg value='-drive'/>"
    if [ $DIR == "null" ]; then
	echo "    <qemu:arg value='file=null-aio://,if=none,size=${SIZE},id=nvme${i},format=null-aio'/>"
    else
	echo "    <qemu:arg value='file=${DIR}/${PREFIX}nvme${i}.qcow2,if=none,id=nvme${i},format=qcow2'/>"
    fi
    echo "    <qemu:arg value='-device'/>"
    echo "    <qemu:arg value='nvme,drive=nvme${i},serial=nvme${i},cmb_size_mb=${CMB}'/>"
    ((i++))
done
echo "  </qemu:commandline>"
