#!/bin/bash
#
# virt-install-bionic
#
# (C) Stephen Bates <sbates@raithlin>
#
# A simple script generate a Ubuntu Bionic Bison based VM. Note that
# in order to get the console to work yo need to add console=ttyS0 to
# the kernel command line params inside the guest.

NAME= ${NAME:-stephen}

virt-install \
--connect qemu:///system \
--name ${NAME} \
--memory 1024 \
--vcpus 1 \
--virt-type kvm \
--disk size=8 \
--graphics none \
--network bridge=virbr0 \
--console pty,target_type=serial \
--location 'http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/' \
--extra-args 'console=ttyS0,115200n8 serial'
