#!/bin/bash
#
# virt-clone-many
#
# (C) Stephen Bates <sbates@raithlin>
#
# A simple script that calls virt-clone a bunch of times but assigning
# sane names and mac addresses to each clone. Also generates a xml
# output that can be used in virsh net-edit default to update the DHCP
# server there to assign sensible IP addresses to the clones.
#
# Now we assume the master VM to be cloned is called ${PREFIX}-1 and
# each clone from that will be ${PREFIX}-N (for N=2,
# 3... $NUM+1).

NUM=${NUM:-1}
PREFIX=${PREFIX:-stephen}
MAC_BASE=${MAC_BASE:-52:54:00:f5:0f:}
MAC=${MAC:-6E}
IP_BASE=${IP_BASE:-192:168.122.}
IP=${IP:-101}
DHCP=${DHCP:-yes}
DUMP_DIR=${DIR:-.virt-clone-many}
LIBVIRT_DIR=${LIBVIRT_DIR:-/var/lib/libvirt/images/}

set +e

rm -rf ${DIR} && mkdir -p ${DIR}

for ((i=2;i<=NUM+1;i++)); do

    THIS_MAC=$(echo "ibase=16;${MAC} " | bc)
    THIS_MAC=$((THIS_MAC+ i - 1))
    THIS_MAC=$(echo "obase=16;${THIS_MAC} " | bc)
    THIS_IP=$(printf "%d" $((IP + i - 1)) )

    virt-clone --original ${PREFIX}-1 \
	 --name ${PREFIX}-$i \
	 --mac ${MAC_BASE}${THIS_MAC} \
	 --file ${LIBVIRT_DIR}/${PREFIX}-${i}.qcow2 \
	 --print-xml > ${DUMP_DIR}/${PREFIX}-${i}.xml

    if [ $DHCP == "yes" ]; then
	echo "    <host mac='${MAC_BASE}${THIS_MAC}' name='pmsummit-${i}' ip='${IP_BASE}${THIS_IP}'/>"
    fi
	 
done

exit

#!/bin/bash
# A code-snippet for generating the vNVDIMMs for SNIA PM Hackathon

NUM=${NUM:-1}
PREFIX=${PREFIX:-pmsummit}
LIBVIRT_DIR=${LIBVIRT_DIR:-/var/lib/libvirt/images/}

for ((i=2;i<=NUM+1;i++)); do
    qemu-img create -f raw ${LIBVIRT_DIR}/${PREFIX}-${i}-nvdimm0.qcow2 1G
    qemu-img create -f raw ${LIBVIRT_DIR}/${PREFIX}-${i}-nvdimm1.qcow2 16M
    chown libvirt-qemu:kvm ${LIBVIRT_DIR}/${PREFIX}-${i}-nvdimm0.qcow2
    chown libvirt-qemu:kvm ${LIBVIRT_DIR}/${PREFIX}-${i}-nvdimm1.qcow2
done

ls -la ${LIBVIRT_DIR}


#!/bin/bash
# A code-snippet for editing the XML in each clone for PM Summit

NUM=${NUM:-1}
PREFIX=${PREFIX:-pmsummit}

set +e

for ((i=2;i<=NUM+1;i++)); do
    virsh dumpxml ${PREFIX}-${i} > temp.xml
    sed -ie "s/${PREFIX}-1-/${PREFIX}-${i}-/" temp.xml
    virsh define temp.xml
done
