#!/bin/bash
#
# virt-install-bionic
#
# (C) Stephen Bates <sbates@raithlin>
#
# A simple script generate a Ubuntu Bionic Bison based VM. Note that
# in order to get the console to work yo need to add console=ttyS0 to
# the kernel command line params inside the guest. Provide the name
# and a kickstart file (which can be used to completely automate the
# install process.
#
# Note that for Eideticom installs you also want to pass in the LDAP
# files via the INITD_INJECT argument.

NAME=${NAME:-stephen}
KS=${KS:-none}
INITRD_INJECT=${INITRD_INJECT:-}

echo ${NAME} > hostname.tmp
INITRD_INJECT+=" --initrd-inject ./hostname.tmp "

if [ $KS != "none" ]; then
    INITRD_INJECT+=" --initrd-inject ./${KS} "
    KSF="ks=file:/${KS}"
else
    KS=
    KSF=
fi

virt-install \
--connect qemu:///system \
--name ${NAME} \
--memory 1024 \
--vcpus 1 \
--virt-type kvm \
--disk size=8 \
--graphics none \
--network bridge=virbr0 \
--console pty,target_type=serial \
--location 'http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/' \
${INITRD_INJECT} \
--extra-args ''${KSF}' console=ttyS0,115200n8 serial'
