#!/bin/bash

SUBSYSTEM=nvmf-test
IP_PORT=1023

# Start the RXE driver
rxe_cfg start

#Sleep for a bit to let network wake up
sleep 5

# Attempt to discover the target. The IP address should be provided
# and the port is as set above.

nvme discover -t rdma -a $1 -s $IP_PORT
nvme connect –t rdma –n ${SUBSYSTEM} -a $1 -s ${IP_PORT}
