#!/bin/bash
# A simple script to call qemu for ppc64el. Note you should build the
# kernel starting from the pseries defconfig to get it to boot
# correctly.

/opt/qemu/qemu-upstream/bin/qemu-system-ppc64 \
    -machine pseries \
    -cpu power8 \
    -smp 1 -m 2048 \
    -kernel ~/kernel/linux-ppc64el/vmlinux \
    -append "nvme.use_cmb=24 console=hvc root=/dev/sda rootwait rw" \
    -serial mon:stdio -drive file=image-ppc64el.img,if=scsi,format=raw,index=0 \
    -nographic \
    -drive file=../images/nvme.qcow2,if=none,id=nvme1,snapshot=on \
    -device nvme,drive=nvme1,serial=nvme1 \
    -drive file=../images/nvme2.qcow2,if=none,id=nvme2,snapshot=on \
    -device nvme,drive=nvme2,serial=nvme2,cmb_size_mb=64
