#!/bin/bash

/opt/qemu/qemu-upstream/bin/qemu-system-ppc64 -machine pseries -cpu POWER8 -nographic -smp 1 -m 2048 -kernel ~/zImage-ppc64el-p2pmem-14.1 -append "nvme.use_cmb=24 root=/dev/hda console=tty0 rootwait rw" -hda image-ppc64el.img -drive file=../images/nvme2.qcow2,if=none,id=nvme2,snapshot=on -device nvme,drive=nvme2,serial=nvme2,cmb_size_mb=64
