#!/bin/bash

#/opt/qemu/qemu-upstream/bin/qemu-system-aarch64 -machine virt -cpu cortex-a57 -machine type=virt -nographic -smp 1 -m 2048 -kernel ~/Image-aarch64-nvmeof-tcp -append "nvme.use_cmb=24 root=/dev/vda console=ttyAMA0 rootwait rw" -drive file=image-arm64.img,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 -drive file=../images/nvme2.qcow2,if=none,id=nvme2,snapshot=on -device nvme,drive=nvme2,serial=nvme2,cmb_size_mb=64

/opt/qemu/qemu-upstream/bin/qemu-system-aarch64 \
    -machine virt \
    -cpu cortex-a57 \
    -nographic \
    -smp 1 -m 2048 \
    -kernel /home/batesste/kernel/linux-arm64/arch/arm64/boot/Image \
    -append "root=/dev/vda console=ttyAMA0 rootwait rw" \
    -device e1000,netdev=user0 \
    -netdev user,id=user0 \
    -drive file=./images/image-arm64.img,if=none,format=raw,id=hd0 \
    -device virtio-blk-device,drive=hd0 \
    -drive file=./images/nvme.qcow2,if=none,id=nvme0,snapshot=on \
    -device nvme,drive=nvme0,serial=nvme0,cmb_size_mb=0 \
    -drive file=./images/nvme2.qcow2,if=none,id=nvme1,snapshot=on \
    -device nvme,drive=nvme1,serial=nvme1,cmb_size_mb=64
