#!/bin/bash

HOST=${HOST:-dev-qemu}
PASSWORD=${PASSWORD:-root}
MOUNT_NVME=${MOUNT_NVME:-no}
DISTRO=${DISTRO:-ubuntu}

set -e

qemu-nbd -c /dev/nbd0 $1
sleep 1
mkdir -p mnt
mount /dev/nbd0p2 mnt

function cleanup {
    set +e
    umount mnt
    qemu-nbd -d /dev/nbd0
}

trap cleanup EXIT

export LANG=C
chroot mnt/ chpasswd <<< root:${PASSWORD}

echo "${HOST}" > mnt/etc/hostname

cat > mnt/etc/hosts << EOF
127.0.0.1   localhost.localdomainlocalhost
127.0.1.1   ${HOST}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

if [ $DISTRO == "debian" ]; then
    FILE=mnt/etc/network/interfaces.d/eth0
elif [ $DISTRO == "ubuntu" ]; then
    FILE=mnt/etc/network/interfaces
else
    echo "${DISTRO} distro not supported by deboostrap"
    exit
fi

cat > ${FILE} << EOF
allow-hotplug eth0
iface eth0 inet dhcp
iface eth0 inet6 auto
EOF

cat > mnt/etc/fstab << EOF
LABEL=swap none  swap   sw   0   0
LABEL=rootfs /     ext4   errors=remount-ro,noatime   0   0
home  /home 9p     trans=virtio,version=9p2000.L,nofail   0   0
EOF

if [ $MOUNT_NVME == "yes" ]; then
    mkdir -p mnt/nvme
cat >> mnt/etc/fstab << EOF
/dev/nvme0n1 /mnt/nvme ext4  noatime,nofail   0   0
EOF
fi

sed -i "s|PermitRootLogin without-password|PermitRootLogin yes|" mnt/etc/ssh/sshd_config

mkdir -p mnt/etc/systemd/system/serial-getty@ttyS0.service.d
cat > mnt/etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin root -s %I 38400 vt102
EOF

echo "setup of $1 complete!"
