#!/bin/bash
# Create really simple initramfs/rootfs

set -e

cat > simple.c << EOF
#include <stdio.h>
#include <unistd.h>

int main(int argc, char *argv)
{
    printf("Hello World!\n");
    sleep(99999999);
}
EOF

gcc -static simple.c -o init
echo init | cpio -o -H newc | gzip > simple.cpio.gz
rm -rf init simple.c
